tap "stripe/stripe-cli"
tap "umputun/apps"

# Shell, Git, navigation, and quality
brew "actionlint"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "htop"
brew "jq"
brew "moor"
brew "ncdu"
brew "pre-commit"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "worktrunk"

# Development runtimes and services
brew "bun"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "libpq"
brew "neovim"
brew "php"
brew "pnpm"
brew "python@3.14"
brew "static-web-server"
brew "tree-sitter-cli"
brew "uv"

# AI and agent tools
brew "gemini-cli"
brew "gitleaks"
brew "herdr"
brew "umputun/apps/ralphex"
brew "umputun/apps/revdiff"

# Media, documents, and integrations
brew "ffmpeg"
brew "poppler"
brew "sox"
brew "stripe/stripe-cli/stripe"
brew "yt-dlp"

# Credentials, AI, and development applications
cask "1password"
cask "1password-cli"
cask "chatgpt"
cask "claude"
cask "codex"
cask "codexbar"
cask "copilot-cli"
cask "cursor"
cask "handy"
cask "lm-studio"
cask "ollama-app"
cask "tableplus"
cask "visual-studio-code"
cask "zed"

# Terminal applications and fonts
cask "umputun/apps/agterm"
cask "wezterm@nightly"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"

# Browsers, communication, and productivity
cask "arc"
cask "discord"
cask "google-chrome"
cask "meetingbar"
cask "obsidian"
cask "raycast"
cask "slack"
cask "tailscale-app"
cask "telegram"
